index/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include,re_path

from account_social import views

urlpatterns = [
    #url(r'^$',include("account_social.urls")),
    url(r'^login/$',views.user_login, name='login'),
    url(r'^logout/$',views.user_logout, name='logout'),
    re_path(r'^dashboard/$',views.dashboard, name='dashboard'),

]

social/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from index import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/',include('account_social.urls')),
    url(r'^registration/',include('registration.urls')),
    re_path(r'^$', views.index),
    path('news/', include('social_content.urls', namespace='social_content')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_content/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from social_content import views

app_name = 'social_content'

urlpatterns = [
    url(r'^create/$', views.content_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.content_detail, name='detail'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.content_edit, name='edit'),
    re_path(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/delete/$', views.delete_content, name='delete'),
    path('like/',views.content_like,name='like'),
    url(r'^add_to_favorites/$',views.AddArticlesToFavorites, name='add_to_favorites'),

]

social_content/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from pytils.translit import slugify
from tinymce.models import HTMLField


class Content(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='content_created', on_delete=models.CASCADE);
    title = models.CharField(max_length=180, unique=True, verbose_name='Введите заголовок')
    slug = models.SlugField(max_length=220, db_index=True, verbose_name='slug')
    image = models.ImageField(upload_to='users/%Y/%m/%d', blank=True, null=True, default='no_image_app_content.png', verbose_name='Загрузить изображение')
    entry = HTMLField(blank=True, verbose_name='Запись')
    created = models.DateTimeField(auto_now_add=True)
    user_likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='content_liked', blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Content, self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('social_content:detail', kwargs={'id':self.id, 'slug':self.slug})

    def __str__(self):
        return self.title


# Create your models here.

social_content/forms.py
from django import forms
from social_content.models import Content

class ContentCreateForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ('title','image', 'entry',)

class DeleteContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = []

social_content/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.views.decorators.http import require_POST

from my_decorators.decorator_ajax import ajax_required
from social_content.forms import ContentCreateForm, DeleteContentForm
from social_content.models import Content
from crispy_forms.helper import FormHelper
from my_decorators import decorator_ajax
from account_social.models import Profile

@login_required
def content_create(request):
    if request.method == 'POST':
        form = ContentCreateForm(request.POST, request.FILES)
        if form.is_valid():
            new_content = form.save(commit=False)
            new_content.user = request.user
            new_content.save()
            return redirect(new_content.get_absolute_url())
    else:
        form = ContentCreateForm()
    return render(request, 'contents/content/create.html', {'form': form, 'username': request.user})

# Create your views here.

def content_detail(request, id, slug):
    content_detail = get_object_or_404(Content, id = id, slug = slug)

    return render(request,
                  "contents/content/detail.html",
                  {'content_detail':content_detail, 'username': request.user})
@login_required
def content_edit(request, id, slug):
        new_content = get_object_or_404(Content, id = id, slug = slug)
        if new_content.user == request.user and not request.user.is_superuser:
            pass

        if request.method == 'POST':
            form = ContentCreateForm(instance=new_content, data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                return redirect(new_content.get_absolute_url())
        else:
            form = ContentCreateForm(instance=new_content)
            context = {'form':form, 'create': False}
            return render(request,'contents/content/create.html', context)

@login_required
def delete_content(request, id, slug):
    new_to_delete = get_object_or_404(Content, id = id, slug = slug)
    if new_to_delete.user != request.user and not request.user.is_superuser:
        messages.error(request,"нет доступа для удаления записи!!!")
        return redirect(new_to_delete.get_absolute_url())
    if request.method == 'POST':
        form = DeleteContentForm(request.POST, instance=new_to_delete)
        if form.is_valid():
            new_to_delete.delete()
            messages.success(request,"Запись удалена");
            return HttpResponseRedirect('/account/news')
    else:
        form = DeleteContentForm(instance=new_to_delete)

    template_vars = {'form':form,}
    return render(request, 'contents/content/delete.html',template_vars)


class Json(object):
    pass

@login_required
@require_POST
@ajax_required
def AddArticlesToFavorites(request):
    content_id = request.POST.get('id')
    content_slug = request.POST.get('slug')
    action = request.POST.get('action')
    content = Content.objects.get(id=content_id)
    current_user = Profile.objects.get(user=request.user)
    print(action)
    if action == 'add_to_favorites':
        current_user.favorite_articles.add(content)
    else:
        current_user.favorite_articles.remove(content)
    current_user.save()
    return JsonResponse({'status':'ok '})

@login_required
@require_POST
@ajax_required
def content_like(request):
    content_id = request.POST.get('id')
    action = request.POST.get('action')

    if content_id and action:
        try:
            content = Content.objects.get(id=content_id)
            if action == 'like':
                content.user_likes.add(request.user)
            else:
                content.user_likes.remove(request.user)
            #JSON
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})

social_content/templates/contents/content/create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %} Добавить новость {% endblock %}
{% block content %}


        <form action="" method="post" name="form" enctype="multipart/form-data">
            {{ form | crispy }}
            {{form.media}}
            {% csrf_token %}
        <input type="submit" value="Сохранить">

    </form>

{% endblock %}

social_content/templates/contents/content/delete.html
{% extends "base.html" %}

{% block content %}

    <form action="." method="post" name="form" enctype="multipart/form-data">

        <h3>Вы уверены, что хотите удалить новость?</h3>
        {% csrf_token %}
        <input type="submit" class="button" value="Удалить"/>
    </form>

{% endblock %}

social_content/templates/contents/content/detail.html
{% extends "base.html" %}
    {% load staticfiles %}
{% block content %}

{% if request.user.is_authenticated %}
    <li class="list-group-item"><b><a href="{% url 'social_content:create'%}">Создать</a></b></li>
{% endif %}

{% if content_detail.user == request.user or request.user.is_superuser%}
<li class="list-group-item"><b><a href="{% url 'social_content:edit' slug=content_detail.slug id=content_detail.id%}">Редактировать</a></b>
<li class="list-group-item"><b><a href="{% url 'social_content:delete' slug=content_detail.slug id=content_detail.id%}">Удалить</a></b>
    {% endif %}




<main role="main" class="container">
    <h1>Автор {{content_detail.user}}</h1>
    <h2>{{content_detail.title}}</h2>
    {% load thumbnail %}
    {% thumbnail content_detail.image "300" as im %}

        <a href="{{ content_detail.image.url }}">
        <img src="{{im.url}}">
    </a>
    {% endthumbnail %}

    <br>
    <br>
    {{content_detail.entry|safe }}


{% with total_likes=content_detail.user_likes.count user_likes=content_detail.user_likes.all %}
 <div class="image-info">
                <div>


<br><hr>


 <!-- End количество просмотров -->

 <!-- likes-->
  <span class="count">
 <span class="total">{{ total_likes }}</span>
like{{ total_likes|pluralize }}
 </span>
 <!--End  likes-->

{% if request.user.is_authenticated %}


                    <a href="#" data-id="{{ content_detail.id }}" data-action="{% if request.user in user_likes %}un{% endif %}like" class="like button">
                        {% if request.user not in user_likes %}
                            <b>Нравится</b>
                        {% else %}
                            <b>Не нравится</b>
                        {% endif %}
                    </a>
                </div>


        </div>


{% else %}
    <br><br>
    {{ content_detail.entry|safe}}


 {% endif %}
<br><br>


        <div class="image-likes">
            {% for user in content_detail.user_likes.all %}
                <div>
                {% if user.profile.photo %}
                   <img src="{{ user.profile.photo.url }}" width="60px" height="60px">
                    {% else %}
                    <img src="{%static "no_image_app_content.png" %}"  width="60px" height="60px">
                    {% endif %}
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Пока нет лайков. Оцените первым.
            {% endfor %}
        </div>
    {% endwith %}

{% with total_favorite_articles=Profille.user_likes.count user_favorite_articles=Profile.user_likes.all %}

<a href='#' class='article' data-action='{% if content_detail in request.user.profile.favorite_articles.all %}remove_from_favorite{%else%}add_to_favorites{% endif %}' data-id="{{ content_detail.id }}" data-slug='{{content_detail.slug}'>
    {% if content_detail in request.user.profile.favorite_articles.all %}
        <b>Отписаться</b>
    {% else %}
        <b>Подписаться</b>
    {% endif %}
    
{% endwith %}
    </main>
{% endblock %}
{% block ajax_and_jquery %}
    $('a.like').click(function(e){
e.preventDefault();

$.post('{% url "social_content:like" %}',
    {
        id: $(this).data('id'),
        action: $(this).data('action')
    },
    function(data){
        if (data['status'] == 'ok')
        {
            var previous_action = $('a.like').data('action');
            // toggle data-action
            $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
            // toggle link text
            $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');


            // update total likes
            var previous_likes = parseInt($('span.count .total').text());
            $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
});


});

$('a.article').click(function(e){
    e.preventDefault();
    var article_slug = $(this).attr('data-slug');
    $.post('{% url "social_content:add_to_favorites" %}',
    {
        id: $(this).data('id'),
        slug: $(this).data('slug'),
        action: $(this).data('action'),
    },
    function(data){
            {
              var previous_action = $('a.article').data('action')
              $('a.article').data('action', previous_action == 'add_to_favorites' ? 'remove_from_favorite':'add_to_favorites' )
              $('a.article').text(previous_action == 'add_to_favorites' ? 'remove_from_favorite':'add_to_favorites');
            }
        });
});

    {% endblock %}